apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-3
spec:
  restartPolicy: Never
  nodeName: talos-2wy-r8a
  containers:
  - name: disk-wipe
    image: busybox
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c", "dd if=/dev/zero bs=1M count=100 oflag=direct of=/dev/sdb"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-4
spec:
  restartPolicy: Never
  nodeName: talos-7lq-e0y
  containers:
  - name: disk-wipe
    image: busybox
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c", "dd if=/dev/zero bs=1M count=100 oflag=direct of=/dev/sdb"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-5
spec:
  restartPolicy: Never
  nodeName: talos-j2u-mvd
  containers:
  - name: disk-wipe
    image: busybox
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c", "dd if=/dev/zero bs=1M count=100 oflag=direct of=/dev/sdb"]