apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - namespace.yaml
  - repository.yaml
  - open-webui-release.yaml
  - litellm-release.yaml
  - secrets.yaml
  - cert.yaml
configMapGenerator:
  - name: open-webui-values
    files:
      - values.yaml=openwebui-values.yaml
  - name: litellm-values
    files:
      - values.yaml=litellm-values.yaml
configurations:
  - kustomizeconfig.yaml