apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ai
spec:
  interval: 10m
  releaseName: open-webui
  chart:
    spec:
      chart: open-webui
      version: 6.22.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
  valuesFrom:
    - kind: ConfigMap
      name: open-webui-values
