apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui
  namespace: default
spec:
  interval: 1m
  url: https://helm.openwebui.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: unique
  namespace: default
spec:
  interval: 5m0s
  url: https://unique-ag.github.io/helm-charts/
