apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phantombot-tls-secret
  namespace: phantombot
spec:
  secretName: phantombot-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bot.stream.ottercloud.net