apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Configure your email here...
    # ---
    email: admin@ottercloud.net

    # Letsencrypt Staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
      # Configure DNS or HTTP Challenge here...
      # ---
      # DNS Challenge:
      - dns01:
          # Configure your DNS Provider here...
          # ---
          cloudflare:
            email: "admin@ottercloud.net"
            # API Token:
            apiTokenSecretRef:
              name: cloudflare-credentials
              key: api-token
