apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - cloudflare-credentials.yaml
  - clusterissuer-letsencrypt-prod.yaml
  - clusterissuer-letsencrypt-staging.yaml
