apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - cert-prod.yaml
configMapGenerator:
  - name: rook-values
    files:
      - values.yaml=rook-values.yaml
configurations:
  - kustomizeconfig.yaml