apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: 2025.6.2
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: default
  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
