apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-frontend
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auth.ottercloud.net
