apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - namespace.yaml
  - repository.yaml
  - authentik-release.yaml
  - secrets.yaml
  - cert.yaml
configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml=authentik-values.yaml
configurations:
  - kustomizeconfig.yaml