apiVersion: v1
kind: Secret
metadata:
    name: authentik-credentials
    namespace: authentik
type: Opaque
stringData:
    mail_host: ENC[AES256_GCM,data:nrAwndqhYx1HvW8NqhMcx0k=,iv:jr5q6u+ULAL4SXQj9w6XzLC+UkpCobDUNDq0dRe+kVA=,tag:KNuEU+I5v2FSUxv/V8VT5A==,type:str]
    mail_port: ENC[AES256_GCM,data:k6BG,iv:vpHFYf7o3g16a/HHAvecGfXDVavFWJyziy7yScqcy2g=,tag:Ip2097TDkUgw5UxGgEKEqw==,type:str]
    mail_tls: ENC[AES256_GCM,data:gJHK8kM=,iv:7tLNdJZgUzyjDDT0zPWXkaSDW1z7KSZf9yZhIAIvGNI=,tag:qn+v50QQsH3gCzFzrTeI8A==,type:str]
    mail_ssl: ENC[AES256_GCM,data:7E9NJg==,iv:mPGzhZducYGld3F3wl26TUwst01KPvZI2434XWvei/g=,tag:pXzsKHeFM6s0WfCKo+lGEw==,type:str]
    mail_user: ENC[AES256_GCM,data:On2artyXkpVoBHjBxAB3pw==,iv:lDz7EsBk30fYhXKDhRFOHzxIjbQIdb8nZObl3oEL65s=,tag:FLy8i0Ntd+ml8TdY9LHraw==,type:str]
    mail_password: ENC[AES256_GCM,data:WwZ+RMfl+vHE/TvVz4/lwApeDK60OrUulnHImAeBUkVh1xfZCg==,iv:E+09zcDVh8Or7RkZS4SmeGKnQoIMkCTJA/c5/CNJOTg=,tag:KiIjVl4I7GvCENRfpYC//Q==,type:str]
    #ENC[AES256_GCM,data:Nr7G/olC5QCprYkR6Bv4vdc55TbPRzGpGmWcxuDPy0Oy8/5Un5chpkObOkyCrgMe9obqBCnrO7X8rsipHMcjStaT1FGNtA==,iv:DvJu0tKLhXiawinffEnRibRuWwzPU1vbOihGE8AZI5Y=,tag:q0hEfwdu+AfQnHpip7eqTw==,type:comment]
    mail_from: ENC[AES256_GCM,data:iGEjzsBRS1dS234sHPKHO2jHweLQjCI7NxWsXw==,iv:Km+kfxmt47N0r941syT34sbfyJi7t/oYmrvfxejNWTI=,tag:fHVu95IZ+33A+wabFHIj8A==,type:str]
    mail_timeout: ENC[AES256_GCM,data:WK8=,iv:Qp7Ia0bQPsv6+u8bXjnGRMLACx3Iz8tgXxjQFXsmZrQ=,tag:2tAAi3igRsW3cAXD7LT75g==,type:str]
    authentik_secret: ENC[AES256_GCM,data:aJVC1fOQ/i6AF/hrAtWO7uQaoCzDachhJ2R0wOoBtfYShnWcy6ytYk3YCcItVuoGhYM=,iv:ITTOALE/ht/rpuo4KcgWYHOl1sYOuZv/NL9knS02hn0=,tag:YSTz0PJjEcdbag5sVA1nZw==,type:str]
    maxmind_license_key: ENC[AES256_GCM,data:qI1LR8Q7M0S6d8SE+50Puxby/XOMZOs0eTXpoyIOVpyc0SDo7T5T3A==,iv:wXHt9stl/HnIZQ6ueX0hru2SElyDaHB32vS3yr/L1x0=,tag:x4LF5xxO8UHMa7u81rjHGQ==,type:str]
    maxmind_account_id: ENC[AES256_GCM,data:BggPjZto,iv:V2QXGNWRh3vTsYiiNpBBl68mdEzuNCk8koWVYCq0vzA=,tag:oq1DJql3pY2qx9t4QKFO7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sq9smym4rpss086f2mzxg9jt98mv9qykt0e2warvla6rxvrvq97sz9pwgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQakkxQWRoTW0vK1Z0NXZt
            dTNOaDRwcDd5aC9tbGI2aXBGMGEvaDVadXlZCkRQNDREN0hIWTZnaVl5eHVod1Nw
            dXh3cm40WnVkSWM5djg2amtOMzZPVDQKLS0tIGpxSGk0YW0zc2FxaUN3THFzVENK
            MVRuczBWSXQ4V1JrNUhjQW1qMzdjamsKN3P1pbpyM9p0GuezxwdvpiP+zz2noucl
            PCE804EkRLT/mbOzEPCkBXt255pb2XmMoPkRrD0BCZwgbtDlEQIjzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-25T14:55:02Z"
    mac: ENC[AES256_GCM,data:4tQ2kNc+ZowmyGb9PuHV0IVkZ+D5AOrO9vKwG8hwEYRc2VDbwPtlyhXrFDfWMAYUBerKGRo3q0GQgx2Ekg4z1ML6yr7yrBwSBA9DkVGHF35908lWKwP5eRnrZHy59zaoHwMzySXit3YGzUGKxjLRqdW8iGS0K3JaxKn9PZAPwbI=,iv:CGBIJgtTz4M0DLwzQWe2qHttrQvfYflY+p2XwdwNXFA=,tag:XYox99etImq0eKX9M6TdoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
