ipam:
  mode: kubernetes

kubeProxyReplacement: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

k8sServiceHost: auto
k8sServicePort: 7445

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: cilium
      hosts:
        - hubble.cilium.ottercloud.net
      tls:
        - hosts:
            - hubble.cilium.ottercloud.net
          secretName: hubble-tls-cert


l2announcements:
  enabled: true

# Calculated based on 30 services
# https://docs.cilium.io/en/latest/network/l2-announcements/#sizing-client-rate-limit

k8sClientRateLimit:
  qps: 15
  burst: 20

ingressController:
  enabled: true
  loadbalancerMode: shared
  default: true

encryption:
  # -- Enable transparent network encryption.
  enabled: true
  # -- Encryption method. Can be either ipsec or wireguard.
  type: wireguard
  # -- Enable encryption for pure node to node traffic.
  # This option is only effective when encryption.type is set to "wireguard".
  nodeEncryption: true
  wireguard:
    persistentKeepalive: 30s


externalIPs:
  # -- Enable ExternalIPs service support.
  enabled: true