apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: 0.38.1
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator
      version: 0.38.1
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
  values:
    webhook:
      cert:
        certManager:
          enabled: true