apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 12h
  path: "./deploy/standalone"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver
  wait: true
  timeout: 5m