apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - cloudflare-credentials.yaml
  - clusterissuer-letsencrypt-prod.yaml
  - clusterissuer-letsencrypt-staging.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=cert-manager-values.yaml
configurations:
  - kustomizeconfig.yaml