apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: apps-pool
  namespace: kube-system
spec:
  blocks:
    - start: "10.8.8.106"
      stop: "10.8.8.150"

  serviceSelector:
    matchLabels:
      cilium-lb-pool: apps-pool
