apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-tls-cert
  namespace: kube-system
spec:
  secretName: hubble-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - hubble.cilium.ottercloud.net
