apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-pool
  namespace: kube-system
spec:
  blocks:
    - start: "10.8.8.200"
      stop: "10.8.8.205"

  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
